#pragma once

#define ENG_PARENS ()

// https://www.scs.stanford.edu/~dm/blog/va-opt.html
#define _ENG_FOR_EACH_EXPAND(...)  _ENG_FOR_EACH_EXPAND4(_ENG_FOR_EACH_EXPAND4(_ENG_FOR_EACH_EXPAND4(_ENG_FOR_EACH_EXPAND4(__VA_ARGS__))))
#define _ENG_FOR_EACH_EXPAND4(...) _ENG_FOR_EACH_EXPAND3(_ENG_FOR_EACH_EXPAND3(_ENG_FOR_EACH_EXPAND3(_ENG_FOR_EACH_EXPAND3(__VA_ARGS__))))
#define _ENG_FOR_EACH_EXPAND3(...) _ENG_FOR_EACH_EXPAND2(_ENG_FOR_EACH_EXPAND2(_ENG_FOR_EACH_EXPAND2(_ENG_FOR_EACH_EXPAND2(__VA_ARGS__))))
#define _ENG_FOR_EACH_EXPAND2(...) _ENG_FOR_EACH_EXPAND1(_ENG_FOR_EACH_EXPAND1(_ENG_FOR_EACH_EXPAND1(_ENG_FOR_EACH_EXPAND1(__VA_ARGS__))))
#define _ENG_FOR_EACH_EXPAND1(...) __VA_ARGS__

#define ENG_FOR_EACH(macro, ...) __VA_OPT__(_ENG_FOR_EACH_EXPAND(_ENG_FOR_EACH_HELPER(macro, __VA_ARGS__)))
#define _ENG_FOR_EACH_HELPER(macro, arg, ...) macro(arg) __VA_OPT__(_ENG_FOR_EACH_AGAIN ENG_PARENS (macro, __VA_ARGS__))
#define _ENG_FOR_EACH_AGAIN() _ENG_FOR_EACH_HELPER

#define ENG_FOR_EACH_ZIP1(macro, zipped, ...) __VA_OPT__(_ENG_FOR_EACH_EXPAND(_ENG_FOR_EACH_ZIP1_HELPER(macro, zipped, __VA_ARGS__)))
#define _ENG_FOR_EACH_ZIP1_HELPER(macro, zipped, arg, ...) macro(zipped, arg) __VA_OPT__(_ENG_FOR_EACH_ZIP1_AGAIN ENG_PARENS (macro, zipped, __VA_ARGS__))
#define _ENG_FOR_EACH_ZIP1_AGAIN() _ENG_FOR_EACH_ZIP1_HELPER

// Second copy so you can nest two for each's.
#define _ENG_FOR_EACH2_EXPAND(...)  _ENG_FOR_EACH2_EXPAND4(_ENG_FOR_EACH2_EXPAND4(_ENG_FOR_EACH2_EXPAND4(_ENG_FOR_EACH2_EXPAND4(__VA_ARGS__))))
#define _ENG_FOR_EACH2_EXPAND4(...) _ENG_FOR_EACH2_EXPAND3(_ENG_FOR_EACH2_EXPAND3(_ENG_FOR_EACH2_EXPAND3(_ENG_FOR_EACH2_EXPAND3(__VA_ARGS__))))
#define _ENG_FOR_EACH2_EXPAND3(...) _ENG_FOR_EACH2_EXPAND2(_ENG_FOR_EACH2_EXPAND2(_ENG_FOR_EACH2_EXPAND2(_ENG_FOR_EACH2_EXPAND2(__VA_ARGS__))))
#define _ENG_FOR_EACH2_EXPAND2(...) _ENG_FOR_EACH2_EXPAND1(_ENG_FOR_EACH2_EXPAND1(_ENG_FOR_EACH2_EXPAND1(_ENG_FOR_EACH2_EXPAND1(__VA_ARGS__))))
#define _ENG_FOR_EACH2_EXPAND1(...) __VA_ARGS__

#define ENG_FOR_EACH2(macro, ...) __VA_OPT__(_ENG_FOR_EACH2_EXPAND(_ENG_FOR_EACH2_HELPER(macro, __VA_ARGS__)))
#define _ENG_FOR_EACH2_HELPER(macro, arg, ...) macro(arg) __VA_OPT__(_ENG_FOR_EACH2_AGAIN ENG_PARENS (macro, __VA_ARGS__))
#define _ENG_FOR_EACH2_AGAIN() _ENG_FOR_EACH2_HELPER

#define ENG_FOR_EACH2_ZIP1(macro, zipped, ...) __VA_OPT__(_ENG_FOR_EACH2_EXPAND(_ENG_FOR_EACH2_ZIP1_HELPER(macro, zipped, __VA_ARGS__)))
#define _ENG_FOR_EACH2_ZIP1_HELPER(macro, zipped, arg, ...) macro(zipped, arg) __VA_OPT__(_ENG_FOR_EACH2_ZIP1_AGAIN ENG_PARENS (macro, zipped, __VA_ARGS__))
#define _ENG_FOR_EACH2_ZIP1_AGAIN() _ENG_FOR_EACH2_ZIP1_HELPER
